#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: users
  datasource:
    url: ${ENV_DB_URL}
    username: ${ENV_DB_USERNAME}
    password: ${ENV_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
  flyway:
    enabled: true